### ISSUE TITLE
Maintanence of project

### ISSUE THREAD

**Issue by eicchen** [LexingtonWhalen/GoogleSubtitleGenerater#1]
I plan to (and kinda am currently) updating the project over on my fork, would you like me to occasionally throw up PRs to merge into the main repo?

 I was planning to add SRT formatting, try out the translations, and see whatever else I can do. 

Currently have added logging and fixed a few other usability issues as well as some documentation mistakes I found when I tried to use it myself

**Comment by lxaw** [comment]
@eicchen02 Thanks for the efforts! Yes, sure! I would love if others update this project, as I had a fun time making it.

Feel free to throw up PRs anytime you wish, and maybe we can make something great!

**Comment by lxaw** [comment]
Conclusion: Whoever wants to help is always welcome.
